"""PipelineRunner: orchestrates the full Loop 3 drawing-to-CAD pipeline."""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from src.inference.base import BaseLLMClient, BaseVisionClient
from src.pipeline.execution_stage import ExecutionStage
from src.pipeline.ocr_stage import OCRStage
from src.pipeline.reasoning_stage import ReasoningStage
from src.pipeline.reconciliation import ReconciliationStage
from src.pipeline.retry_controller import RetryController
from src.pipeline.validation_stage import ValidationStage
from src.pipeline.vision_stage import VisionStage
from src.schemas.evaluation_result import EvaluationMetrics
from src.schemas.geometry import ReconciledGeometry
from src.schemas.pipeline_config import PipelineConfig
from src.utils.logging_config import get_logger

logger = get_logger(__name__)


@dataclass
class PipelineResult:
    """Full result of a pipeline run."""
    success: bool = False
    step_file: Optional[str] = None
    generated_code: str = ""
    reconciled_geometry: Optional[ReconciledGeometry] = None
    metrics: EvaluationMetrics = field(default_factory=EvaluationMetrics)
    retry_count: int = 0
    error: str = ""


class PipelineRunner:
    """Orchestrates the full drawing-to-CAD pipeline (Loop 3)."""

    def __init__(
        self,
        config: PipelineConfig,
        llm_client: BaseLLMClient | None = None,
        vision_client: BaseVisionClient | None = None,
        use_mock: bool = False,
    ):
        self.config = config
        self.llm_client = llm_client
        self.vision_client = vision_client
        self.use_mock = use_mock

        # Initialize stages
        self.vision_stage = VisionStage(config, vision_client)
        self.ocr_stage = OCRStage(config, use_mock=use_mock)
        self.reconciliation_stage = ReconciliationStage(config, llm_client)
        self.reasoning_stage = ReasoningStage(config, llm_client)
        self.execution_stage = ExecutionStage(config)
        self.validation_stage = ValidationStage(config)

    def run(
        self,
        image_path: str | Path,
        output_path: str | None = None,
        fewshot_examples: list[str] | None = None,
    ) -> PipelineResult:
        """Run the full pipeline on a single drawing.
        
        Args:
            image_path: Path to the engineering drawing image.
            output_path: Path for the output STEP file.
            fewshot_examples: Optional few-shot examples for reasoning.
        
        Returns:
            PipelineResult with all outputs.
        """
        if output_path is None:
            output_path = self.config.output.default_step_path

        result = PipelineResult()
        retry_ctrl = RetryController(self.config)

        try:
            # 1. Vision: extract geometry from image
            logger.info("pipeline_step", step="vision", image=str(image_path))
            geometry = self.vision_stage.run(image_path)

            # 2. OCR: supplement with text extraction
            logger.info("pipeline_step", step="ocr")
            enriched = self.ocr_stage.run(image_path, geometry)

            # 3. Reconciliation: merge views into 3D description
            logger.info("pipeline_step", step="reconciliation")
            reconciled = self.reconciliation_stage.run(enriched)
            result.reconciled_geometry = reconciled

            # 4. Reasoning + Execution + Retry loop
            while True:
                error_context = retry_ctrl.build_error_context()
                previous_code = retry_ctrl.get_previous_code()

                # Generate code
                logger.info("pipeline_step", step="reasoning", attempt=retry_ctrl.attempt)
                code = self.reasoning_stage.run(
                    reconciled=reconciled,
                    error_context=error_context,
                    previous_code=previous_code,
                    fewshot_examples=fewshot_examples,
                )

                if not code:
                    result.error = "No code generated by reasoning stage"
                    break

                result.generated_code = code

                # Execute code
                logger.info("pipeline_step", step="execution", attempt=retry_ctrl.attempt)
                exec_result = self.execution_stage.run(code, output_path)

                retry_ctrl.record_attempt(code, exec_result)

                if exec_result.success:
                    result.success = True
                    result.step_file = exec_result.output_file

                    # Validate
                    logger.info("pipeline_step", step="validation")
                    validation, dim_checks, feat_checks = self.validation_stage.run(
                        output_path, reconciled
                    )

                    # Compute metrics
                    result.metrics.execution_success = True
                    result.metrics.validation = validation
                    result.metrics.dimension_checks = dim_checks
                    result.metrics.feature_checks = feat_checks
                    result.metrics.geometry_valid = 1.0 if validation.is_valid else 0.0

                    if dim_checks:
                        passed = sum(1 for d in dim_checks if d.within_tolerance)
                        result.metrics.dimension_fidelity = passed / len(dim_checks)

                    if feat_checks:
                        found = sum(1 for f in feat_checks if f.found)
                        result.metrics.feature_recall = found / len(feat_checks)
                        total_found = sum(1 for f in feat_checks if f.found)
                        result.metrics.feature_precision = (
                            total_found / len(feat_checks) if feat_checks else 0.0
                        )

                    break

                # Check retry
                if not retry_ctrl.should_retry(exec_result):
                    result.error = exec_result.stderr or "Execution failed"
                    break

            result.retry_count = retry_ctrl.attempt
            result.metrics.retry_count = retry_ctrl.attempt
            result.metrics.retry_efficiency = 1.0 - min(retry_ctrl.attempt, 3) / 3.0
            result.metrics.compute_composite(
                self.config.evaluation.weights.model_dump()
            )

        except Exception as e:
            logger.error("pipeline_error", error=str(e))
            result.error = str(e)

        logger.info(
            "pipeline_complete",
            success=result.success,
            retry_count=result.retry_count,
            composite_score=result.metrics.composite_score,
        )
        return result
